[package]
name = "openedx-admin-backend"
version = "0.1.0"
authors = ["dikuchan <dikuchan@yahoo.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
actix-cors = "0.2"

# Logging.
dotenv = "0.15"
log = "0.4"
env_logger = "0.7.1"